<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/18 23:02:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=trails',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
